{% set name = "stopwordsiso" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 10c1cf5df1c31646175178b0b13f0bd2e622384f4a3554986ed3acf85d73c9f0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - setuptools

test:
  imports:
    - stopwordsiso
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/stopwords-iso/stopwords-iso
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Collection of stopwords for multiple languages. Using ISO 639-1 language code.

extra:
  recipe-maintainers:
    - dcfidalgo
